#@ load("@ytt:data","data")
---
apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-key
  namespace: #@ data.values.system_namespace
type: Opaque
data:
  api-key: "b39a95cb0221a990c05cf5bc15dd523f"
