#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-metadata
  namespace: #@ data.values.namespace
  labels:
    app: cf-metadata
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cf-metadata
  template:
    metadata:
      labels:
        app: cf-metadata
      annotations:
        pre.hook.backup.velero.io/command: '["/bin/bash", "-c", "/cnb/process/generate-metadata"]'
    spec:
      imagePullSecrets:
      - name: registry-credentials-cf-metadata
      containers:
      - image: cfcapidocker/backup-metadata@sha256:39d3ef4edb6f49a758bf8f6cf5e57b108dba31f327b0046906fa92f451ca456e
        name: cf-metadata
        command: ["/cnb/process/wait"]
        env:
        - name: CF_API
          value: #@ data.values.cf.api
        - name: CF_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cf-credentials-cf-metadata
        - name: CF_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cf-credentials-cf-metadata
