#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-metadata
  namespace: #@ data.values.namespace
  labels:
    app: cf-metadata
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cf-metadata
  template:
    metadata:
      labels:
        app: cf-metadata
      annotations:
        pre.hook.backup.velero.io/command: '["/bin/bash", "-c", "/backup-metadata"]'
    spec:
      imagePullSecrets:
      - name: registry-credentials-cf-metadata
      containers:
      - image: cfcapidocker/backup-metadata@sha256:056082bbdb4efed69db6c81c398857ce5d50b381ac5323ec208683d9c840811c
        name: cf-metadata
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        env:
        - name: CF_API
          value: #@ data.values.cf.api
        - name: CF_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cf-credentials-cf-metadata
        - name: CF_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cf-credentials-cf-metadata
