#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-metadata
  namespace: #@ data.values.namespace
  labels:
    app: cf-metadata
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cf-metadata
  template:
    metadata:
      labels:
        app: cf-metadata
      annotations:
        pre.hook.backup.velero.io/command: '["/cnb/process/generate-metadata"]'
    spec:
      imagePullSecrets:
      - name: registry-credentials-cf-metadata
      containers:
      - image: cfcapidocker/backup-metadata@sha256:8ec3709d8f0125853d55b56e7ea6847279cf45f6ac4cbe10482c0220e300df72
        name: cf-metadata
        command: ["/cnb/process/wait"]
        env:
        - name: CF_API_HOST
          value: #@ data.values.cf.api
        - name: CF_CLIENT
          valueFrom:
            secretKeyRef:
              key: username
              name: cf-credentials-cf-metadata
        - name: CF_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: password
              name: cf-credentials-cf-metadata
