#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-metadata
  namespace: #@ data.values.namespace
  labels:
    app: cf-metadata
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cf-metadata
  template:
    metadata:
      labels:
        app: cf-metadata
      annotations:
        pre.hook.backup.velero.io/command: '["/cnb/process/web"]' # `/cnb/process/web` runs the built binary
    spec:
      imagePullSecrets:
      - name: registry-credentials-cf-metadata
      containers:
      - image: cfcapidocker/backup-metadata@sha256:aae7f9ef8e77d2670aaec90c421a7b92f21f31ff676775ff249f29b0be490957
        name: cf-metadata
        command: ["/cnb/process/wait"]
        env:
        - name: CF_API
          value: #@ data.values.cf.api
        - name: CF_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cf-credentials-cf-metadata
        - name: CF_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cf-credentials-cf-metadata
